[package]
name = "web_stack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.90"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "console"] }